export const APPLICATION_NAME = 'API-консолька'
export const LOGIN_PAGE_ERROR = 'Вход не вышел'
export const LOGIN_PAGE_LOGIN = 'Логин'
export const LOGIN_PAGE_DESCRIPTION_INPUT = 'Опционально'
export const LOGIN_PAGE_SUBLOGIN = 'Сублогин'
export const LOGIN_PAGE_PASSWORD = 'Пароль'
export const LOGIN_PAGE_LINKTOGITHAB = '@github.com/Giridhar108/hivexSS'
export const CONSOLE_EXIT = 'Выйти'